---
title: "Monthly Expenses"
author: "Kevin"
date: "`r Sys.Date()`"
output: html_document
---

```{r knitr_setup, echo = F}
knitr::opts_chunk$set(echo = F, 
                      message = F, 
                      warning = F, 
                      fig.width = 8, 
                      fig.height = 5, 
                      fig.align = "center")
```

```{r setup}
library(dplyr)
library(ggplot2)
library(plotly)
load("monthly-expenses.RData")
```

## Monthly Expenses

```{r expenses}
gg <- ggplot(by_month, aes(month, Amount)) 
# dashed line for how much I make each month
gg <- gg + 
  geom_hline(yintercept = 1483.16 * 2, colour = "darkgrey", linetype = "dashed")
gg <- gg + geom_text(aes(x = 2, y = 1483.16*2 + 50, 
                          label = "Monthly Earnings"))

# points for total amount spent by category
# this allows me to create custom tooltips
gg <- gg + 
  geom_point(aes(y = tot_Amount, colour = Category, text = Reason), 
             alpha = .5) + 
  scale_colour_brewer(type = "qual", palette = 2, guide = F)

# shaded area plot for expenses
gg <- gg + 
  geom_area(aes(fill = Category), alpha = .3) + 
  scale_fill_brewer(type = "qual", palette = 2, guide = F)


gg <- gg + theme_bw()
gg <- gg + theme(
  panel.grid = element_blank(), 
  panel.border = element_blank()
)
# gg

ggplotly(gg, tooltip = c("x", "y", "colour", "text"))

```

## All Expenses

```{r all}
qplot(Date, Amount, data = dat, colour = Category) %>% 
  ggplotly()
```

